"""empty message

Revision ID: 0b5109af98fa
Revises: 5e1130eda5b2
Create Date: 2022-08-31 10:22:40.328240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b5109af98fa'
down_revision = '5e1130eda5b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('comments', sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint('post_likes_post_id_fkey', 'post_likes', type_='foreignkey')
    op.create_foreign_key(None, 'post_likes', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.add_column('posts', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('posts', sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'updated_on')
    op.drop_column('posts', 'created_on')
    op.drop_constraint(None, 'post_likes', type_='foreignkey')
    op.create_foreign_key('post_likes_post_id_fkey', 'post_likes', 'posts', ['post_id'], ['id'])
    op.drop_column('comments', 'updated_on')
    op.drop_column('comments', 'created_on')
    # ### end Alembic commands ###
