"""empty message

Revision ID: 6436f89c606f
Revises: cb1b83df7f45
Create Date: 2022-08-10 16:47:03.858771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6436f89c606f'
down_revision = 'cb1b83df7f45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_post_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_post_id_fkey', 'comments', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###
