"""empty message

Revision ID: d97d13f0db83
Revises: fdea63eae78a
Create Date: 2022-10-30 12:25:00.925686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd97d13f0db83'
down_revision = 'fdea63eae78a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('friends', 'accepted',
               existing_type=sa.String(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('friends', 'accepted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
