"""empty message

Revision ID: fdea63eae78a
Revises: 0b5109af98fa
Create Date: 2022-10-30 11:33:53.512958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdea63eae78a'
down_revision = '0b5109af98fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friends', sa.Column('sender_id', sa.Integer(), nullable=False))
    op.add_column('friends', sa.Column('reciever_id', sa.Integer(), nullable=False))
    op.add_column('friends', sa.Column('accepted', sa.Boolean(), nullable=True))
    op.drop_constraint('friends_user_a_id_fkey', 'friends', type_='foreignkey')
    op.drop_constraint('friends_user_b_id_fkey', 'friends', type_='foreignkey')
    op.create_foreign_key(None, 'friends', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'friends', 'users', ['reciever_id'], ['id'], ondelete='CASCADE')
    op.drop_column('friends', 'user_b_id')
    op.drop_column('friends', 'user_a_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friends', sa.Column('user_a_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('friends', sa.Column('user_b_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'friends', type_='foreignkey')
    op.drop_constraint(None, 'friends', type_='foreignkey')
    op.create_foreign_key('friends_user_b_id_fkey', 'friends', 'users', ['user_b_id'], ['id'])
    op.create_foreign_key('friends_user_a_id_fkey', 'friends', 'users', ['user_a_id'], ['id'])
    op.drop_column('friends', 'accepted')
    op.drop_column('friends', 'reciever_id')
    op.drop_column('friends', 'sender_id')
    # ### end Alembic commands ###
